#!/bin/bash

############################################
# install.sh                               #
# Junhyeok Ahn ( junhyeokahn91@gmail.com ) #
############################################

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

for rc in bashrc bash_profile bash_prompt vimrc tmux.conf; do
  mkdir -pv bak
  [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
  ln -sfv $BASE/$rc ~/.$rc
done

if [ $(uname -s) = 'Darwin' ]; then
  # Homebrew
  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  echo "Updating homebrew"
  brew install git tmux vim reattach-to-user-namespace ctags-exuberant cmake

  brew tap waltarix/homebrew-customs
  brew install waltarix/homebrew-customs/tmux

  brew cask install iterm2
  xcode-select --install
fi


git config --global user.email "junhyeokahn91@gmail.com"
git config --global user.name "junhyeokahn"

source ./install-vim
